language: cpp
compiler: gcc
sudo: false

addons:
  apt:
    packages:
    - wx-common
    - libwxbase3.0-0
    - libwxbase3.0-dev

before-install:
  - chmod +x configure
install: ./configure && make && make-install
