language: cpp
compiler: gcc
sudo: false

addons:
  apt:
    packages:
    - wx-common
    - libwxbase3.0-0
    - libwxbase3.0-dev
    - libwxbase2.8-0
    - libwxbase2.8-dev

before_install:
  - cp README.MD README
  - autoreconf -vfi
  - chmod +x configure

install:
  - echo "Running ./configure --prefix=$HOME/accountit_build && make && make install"
  - ./configure --prefix=$HOME/accountit_build && make && make install